import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '@/src/Components/Navbar/Navbar'
import { Footer } from '@/src/Components/Footer/Footer'
import { HomeHeader } from '@/src/Components/Home/HomeHeroHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
